- name: Billing & Payments Suggestion Box Template
  description: Suggestions to Money Support Operations regarding Billing &
  Payments
  title: [Date - MMM. DD/YY]
  labels: ["Suggestion"]
  assignees:
- 
  body:
    - type: markdown
      attributes:
        value: |
          **Please update the title to reflect [Date] [Suggestion topic]
          Brief title. Ex: [Jan. 4/22] [Payments] Change to Money Support
          Operations Playbook**
    - type: drondown
      id: Topic
      attributes:
        label: This Suggestion Pertains to
        description: Please indicate the product this suggestion is
        related to (Billing, Payments, Installments)
        options:
          - Billing
          - Payments
          - Installments
          - Other
